<script>
	import { page } from '$app/stores';
	import BackArrow from '$lib/icons/BackArrow.svg';
	import { onMount } from 'svelte';

	/*
	This component is called from TopBackground.svelte component.
	 */

	let html2pdf;
	let isOilPage;
	let isBlendPage;
	$: isOilPage = $page.url.pathname.startsWith('/oils/') && $page.url.pathname.includes('-oil');
	$: isBlendPage = $page.url.pathname.startsWith('/oils/') && $page.url.pathname.includes('-blend');


	onMount(async () => {
		const module = await import('html2pdf.js');
		html2pdf = module.default;
		console.log('html2pdf', html2pdf);
	});

	function generatePDF() {
		const element = document.getElementById('main');
		const additionalElement = document.createElement('div');
		additionalElement.innerHTML = `
			<div class='text-center text-xs text-gray-500 mt-2'>
				<p>Generated by <a href='https://www.oilblends.co' class='underline'>OilBlends</a></p>
			</div>
		`;
		element.appendChild(additionalElement);
		const opt = {
			margin: 10,
			filename: 'oil.pdf',
			image: { type: 'png', quality: 0.5 },
			html2canvas: { scale: 2, useCORS: true },
			jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
		};
		html2pdf().set(opt).from(element).save();

	}
</script>

<!-- This component is called from index.layout.svelte file -->

{#if isOilPage || isBlendPage}
	<button on:click={() => generatePDF()}
					class='flex items-center mt-4 px-1 py-1.5 pr-2  w-fit background-faded rounded-xl'
					style='background: rgba(255, 255, 255, 0.6)'>
		<img src={BackArrow} alt='back arrow' class='h-4 w-4'>Export PDF
	</button>
{/if}